Window = {
    Width = 900
    Height = 900
    Title = "Foxtrot"
}

Scene = "Demo"
// blockout = "./Data/blockouts/bo0.prx"
blockout = "./Data/blockouts/bo1.prx"

HeadBob = {
	Enabled = $True
	ScaleX = 0.076
	ScaleY = 0.077
}
