#pragma once

#include <Core/Ref.hpp>
#include <Math/Vec2.hpp>
#include <Renderer/Backend/GpuBuffer.hpp>
#include <Renderer/PrimitiveMesh.hpp>

namespace fx {

class Image;

} // namespace fx

namespace fx::renderer {

class CommandBuffer;
class Sampler;

/**
 * @brief Draws 2D bitmap text (from Textures/square_6x6.png) in screen space.
 *
 * Glyphs are rendered as instanced quads generated by MeshGen. Each instance carries its
 * pixel-space position/size and atlas UVs, and is fetched by the vertex shader from a
 * structured storage buffer via SV_InstanceID.
 */
class TextRenderer
{
public:
	static constexpr uint32 scMaxGlyphs = 2048;
	/// Size in texels of a single glyph in the source atlas (square_6x6.png).
	static constexpr uint32 scGlyphTexels = 6;
	/// Number of glyph columns in the atlas.
	static constexpr uint32 scAtlasColumns = 13;
	/// Number of glyph rows in the atlas.
	static constexpr uint32 scAtlasRows = 7;

	struct InstanceData
	{
		float vPosition[2]; // Top-left corner in pixel space
		float vSize[2];		// Glyph size in pixel space
		float vUvMin[2];	// Atlas UV of top-left of the glyph
		float vUvMax[2];	// Atlas UV of bottom-right of the glyph
	};

public:
	TextRenderer() = default;
	TextRenderer(TextRenderer& other) = delete;
	TextRenderer operator=(TextRenderer& other) = delete;

	void Create();
	void Destroy();

	/**
	 * @brief Renders a single line of text.
	 * @param cmd Active command buffer (must be within a render stage).
	 * @param text NUL-terminated string to render.
	 * @param position Top-left pixel position of the first glyph.
	 * @param scale Glyph scaling factor (1.0 = native 6x6 px font size).
	 * @param uiColor Linear text color (see Color::AsUInt()).
	 */
	void Render(const CommandBuffer& cmd, const char* text, const Vec2f& position, float32 scale, uint32 uiColor);

	Image* GetAtlas() const { return mpAtlas; }
	renderer::Sampler* GetSampler() const { return mpSampler; }
	RawGpuBuffer& GetInstanceBuffer() { return mInstanceBuffer; }

	~TextRenderer();

private:
	Ref<PrimitiveMesh> mpQuad;
	Image* mpAtlas = nullptr;
	Sampler* mpSampler = nullptr;
	RawGpuBuffer mInstanceBuffer;
};

} // namespace fx::renderer
